### ISSUE TITLE
Core: common security configuration order conflict

### ISSUE THREAD

**Issue by ilayaperumalg** [spring-cloud-stream-app-starters/core#57]
With the common security configuration class `SecurityCommonAutoConfiguration`'s DisableSecurityConfiguration using the default `Order` of `WebSecurityConfigurerAdapter` which is 100, the other `WebSecurityConfigurerAdapter` in the same application configuration conflicts.

For instance, the `http` source app doesn't start with this and through the following:

`
Caused by: java.lang.IllegalStateException: @Order on WebSecurityConfigurers must be unique. Order of 100 was already used on org.springframework.cloud.stream.app.http.source.HttpSourceConfiguration$HttpSourceSecurityConfiguration$$EnhancerBySpringCGLIB$$50356d4e@55562aa9, so it cannot be used on org.springframework.cloud.stream.app.security.common.SecurityCommonAutoConfiguration$DisableSecurityConfiguration$$EnhancerBySpringCGLIB$$57f5ab9a@3bd418e4 too.
`

**Comment by artembilan** [comment]
The point is that https://github.com/spring-cloud-stream-app-starters/http/pull/25 hasn't been merged yet.
The idea is to eliminate that home made security conflict in the HTTP Source in favor of this in the Core.

So, your concern is really valid, but the fix doesn't bring too much sense.
The issue is going to be fixed automatically when that PR is merged.

Thanks for understanding.

P.S. I would reject PR for this issue, but I would like to hear some other opinions.
/CC @tzolov

**Comment by ilayaperumalg** [comment]
@artembilan Thanks! I didn't realize we have that Http PR opened. My concern was that we can't really fix a specific order for this security configuration as it would conflict anyway for any other app. But, given this `common security` is only for the out of the box app starters, I am OK with closing this in favor of the http PR.
